{{- if .Values.deploy.redis }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: voting-app
    component: redis
    tenant: {{ .Values.tenantName | default "shared" }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: voting-app
    component: redis
{{- end }}
