apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'git@github.com:Henry-UN/multi-tenant-deployment.git'
        revision: main
        files:
          - path: tenants/*.yaml
          - path: tenants/tenants.yaml
            exclude: true
  template:
    metadata:
      name: 'voting-app-tenant-{{.name}}'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:Henry-UN/multi-tenant-deployment.git'
        targetRevision: main
        path: .
        helm:
          valueFiles:
            - 'values/{{.valuesFile}}'
          parameters:
            - name: namespace
              value: 'tenant-{{.name}}'
            - name: tenantName
              value: '{{.name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'tenant-{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
